name: hypergaragesale
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  fluttertoast:

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.0+3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.11.0
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

